name: Release Notifications

on:
  delete:
    branches:
      - release/*

jobs:
  release:
    name: Post notification comments on PRs
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            Release {release_link} addresses this.
